<div class="pmpro_testimonial__rating_stars">Stars: <?php echo $testimonial->get_stars(); ?></div>
<div class="pmpro_testimonial__rating">Rating: <?php echo $testimonial->get_rating(); ?></div>
<div class="pmpro_testimonial__title">Title: <?php echo $testimonial->get_title(); ?></div>
<div class="pmpro_testimonial__testimonial">Testimonial: <?php echo $testimonial->get_testimonial(); ?></div>
<div class="pmpro_testimonial__name">Name: <?php echo $testimonial->get_name(); ?></div>
<div class="pmpro_testimonial__job_title">Job Title: <?php echo $testimonial->get_job_title(); ?></div>
<div class="pmpro_testimonial__company">Company: <?php echo $testimonial->get_company(); ?></div>
<div class="pmpro_testimonial__url">URL: <?php echo $testimonial->get_url(); ?> / <?php echo $testimonial->get_url( true, true, 'Visit website' ); ?></div>
<div class="pmpro_testimonial__categories">Cats: <?php echo $testimonial->get_categories(); ?></div>
<div class="pmpro_testimonial__tags">Tags: <?php echo $testimonial->get_tags(); ?></div>
<div class="pmpro_testimonial__image">Image: <?php echo $testimonial->get_image(); ?></div>
